"""Constants for the Window Climate Advisor integration."""

from typing import Final

DOMAIN: Final = "window_climate_advisor"
VERSION: Final = 3

SUBENTRY_TYPE_ROOM: Final = "room"
SUBENTRY_TYPE_OPENING: Final = "opening"

CONF_NAME: Final = "name"
CONF_OUTDOOR_TEMPERATURE_ENTITY_ID: Final = "outdoor_temperature_entity_id"
CONF_WEATHER_ENTITY_ID: Final = "weather_entity_id"
CONF_SOLAR_RADIATION_ENTITY_ID: Final = "solar_radiation_entity_id"
CONF_WIND_SPEED_ENTITY_ID: Final = "wind_speed_entity_id"
CONF_WIND_DIRECTION_ENTITY_ID: Final = "wind_direction_entity_id"
CONF_WIND_GUST_ENTITY_ID: Final = "wind_gust_entity_id"
CONF_RAIN_ENTITY_ID: Final = "rain_entity_id"

CONF_TEMPERATURE_ENTITY_ID: Final = "temperature_entity_id"
CONF_HUMIDITY_ENTITY_ID: Final = "humidity_entity_id"
CONF_CO2_ENTITY_ID: Final = "co2_entity_id"

CONF_ROOM_SUBENTRY_ID: Final = "room_subentry_id"
CONF_FACADE_AZIMUTH_DEG: Final = "facade_azimuth_deg"
CONF_WIDTH_M: Final = "width_m"
CONF_HEIGHT_M: Final = "height_m"
CONF_OVERHANG_DEPTH_M: Final = "overhang_depth_m"
CONF_OVERHANG_GAP_M: Final = "overhang_gap_m"
CONF_SUPPORTS_TILT: Final = "supports_tilt"
CONF_RAIN_PROTECTED: Final = "rain_protected"
CONF_HAS_BLIND: Final = "has_blind"
CONF_CONTACT_ENTITY_ID: Final = "contact_entity_id"
CONF_COVER_ENTITY_ID: Final = "cover_entity_id"

CONF_SELECTION_MODE: Final = "selection_mode"
CONF_SUMMER_LOWER_C: Final = "summer_lower_c"
CONF_SUMMER_UPPER_C: Final = "summer_upper_c"
CONF_SUMMER_PRECONDITIONING_TARGET_C: Final = "summer_preconditioning_target_c"
CONF_SUMMER_HYSTERESIS_C: Final = "summer_hysteresis_c"
CONF_SHOULDER_LOWER_C: Final = "shoulder_lower_c"
CONF_SHOULDER_UPPER_C: Final = "shoulder_upper_c"
CONF_SHOULDER_PRECONDITIONING_TARGET_C: Final = "shoulder_preconditioning_target_c"
CONF_SHOULDER_HYSTERESIS_C: Final = "shoulder_hysteresis_c"
CONF_WINTER_LOWER_C: Final = "winter_lower_c"
CONF_WINTER_UPPER_C: Final = "winter_upper_c"
CONF_WINTER_PRECONDITIONING_TARGET_C: Final = "winter_preconditioning_target_c"
CONF_WINTER_HYSTERESIS_C: Final = "winter_hysteresis_c"

CONF_BLIND_STEP_PERCENT: Final = "blind_step_percent"
CONF_WINDOW_MOVEMENT_PENALTY_W: Final = "window_movement_penalty_w"
CONF_BLIND_FULL_TRAVEL_PENALTY_W: Final = "blind_full_travel_penalty_w"
CONF_MISSING_FORECAST_CHANGE_PENALTY_W: Final = "missing_forecast_change_penalty_w"
CONF_MINIMUM_BENEFIT_W: Final = "minimum_benefit_w"
CONF_BLIND_DEADBAND_PERCENT: Final = "blind_deadband_percent"
CONF_SOURCE_STALE_MINUTES: Final = "source_stale_minutes"
